# Generated by Django 4.2.3 on 2023-07-11 23:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('surname', models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=75, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='Address')),
                ('company', models.CharField(blank=True, max_length=140, null=True, verbose_name='Company')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('surname', models.CharField(blank=True, max_length=75, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=75, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='Address')),
                ('company', models.CharField(blank=True, max_length=140, null=True, verbose_name='Company')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'Suppliers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RawOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Title')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), max_digits=10, null=True, verbose_name='Order Quantity')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Fulfilled Order Quantity')),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('FAIL', 'FAIL'), ('SUCCESS', 'SUCCESS')], default='WAITING', max_length=150, verbose_name='Order Status')),
                ('delivery_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated Data')),
                ('data', models.JSONField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.raw', verbose_name='Raw Material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Raw Material Order',
                'verbose_name_plural': 'Raw Material Orders',
                'db_table': 'Raw_Material_Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Order Title')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), max_digits=10, null=True, verbose_name='Order Quantity')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Fulfilled Order Quantity')),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('FAIL', 'FAIL'), ('SUCCESS', 'SUCCESS')], default='WAITING', max_length=150, verbose_name='Order Status')),
                ('delivery_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('data', models.JSONField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client', verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Order',
                'verbose_name_plural': 'Product Orders',
                'db_table': 'Product_Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DamagedRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Data')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.raw', verbose_name='Raw Material')),
                ('raw_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.raworder', verbose_name='Raw Material Order')),
            ],
            options={
                'verbose_name': 'Damaged Raw Material',
                'verbose_name_plural': 'Damaged Raw Materials',
                'db_table': 'Damaged_Raw_Materials',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DamagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Data')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productorder', verbose_name='Product Order')),
            ],
            options={
                'verbose_name': 'Damaged Product',
                'verbose_name_plural': 'Damaged Products',
                'db_table': 'Damaged_Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Total Revenue')),
                ('total_outcome', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Total Expense')),
                ('salaries', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Salaries')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Overall Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Data')),
                ('product_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.productorder', verbose_name='Product Order')),
                ('raw_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.raworder', verbose_name='Raw Material Order')),
            ],
            options={
                'verbose_name': 'Income/Expense',
                'verbose_name_plural': 'Income/Expense',
                'db_table': 'Income_Expense',
                'ordering': ('-created_at',),
            },
        ),
    ]
