# Generated by Django 4.2.3 on 2023-07-11 23:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), max_digits=10, null=True, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productstock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.rawstock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
                'db_table': 'Raw_Materials',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RawForProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_for_prod', models.IntegerField(default=1, verbose_name='Quantity Required for Production')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='product.product', verbose_name='Product')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.raw', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'Raw Material for Production',
                'verbose_name_plural': 'Raw Material for Production',
                'db_table': 'Raw_Material_for_Production',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Attr',
                'verbose_name_plural': 'Product Attrs',
                'db_table': 'Product_Attrs',
            },
        ),
    ]
